[build]
    publish = "build"
    command = "lektor build --output-path ./build"

[[redirects]]
    from = "/photos"
    to = "http://flickriver.com/photos/istevens/popular-interesting/"
    status = 302

[[redirects]]
    from = "/resume"
    to = "https://drive.google.com/uc?export=download&id=0B2xDdQg0Z1RieEpaWk5SUFJIMHc"
    status = 302
